name: smartlist-budget
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2022 Author name here
license: BSD3
homepage: https://github.com/mtirao/smartlist_budget
source-dirs:
- src
- src/db
- src/controller
- src/dto
- src/helpers
- src/repository
- src/service
extra-source-files:
- README.md
default-extensions:
- DuplicateRecordFields
- DeriveAnyClass
- DerivingStrategies
- OverloadedStrings
- OverloadedRecordDot
- TemplateHaskell
- QuasiQuotes
ghc-options:
- -threaded
- -O2
- -rtsopts
- -with-rtsopts=-N
- -Wno-deprecations
- -Wno-unused-imports
- -Wno-type-equality-out-of-scope
- -Wno-type-equality-requires-operators
dependencies:
- base >=4.14.3.0
- scotty
- bytestring
- text
- postgresql-simple
- aeson
- transformers
- wai
- wai-middleware-static
- wai-extra
- resource-pool
- configurator
- MissingH
- lens
- lens-aeson
- wreq
- http-types
- time
- warp-tls
- warp
- bytestring-conversion
- jose-jwt
- hasql
- rel8
- uuid
executables:
  smartlist-budget:
    main: Main.hs
